[workspace]
resolver = "3"
members = ["core", "protocol"]
[workspace.dependencies]
tokio = "1.44.2"
tokio-util = "0.7.14"
serde = "1.0.219"
bytes = { version = "1.10.1", features = ["serde"] }
thiserror = "2.0.12"
bincode = "2.0.1"
tracing = "0.1.41"
